:source-highlighter: coderay
:icons: font
:icon-set: fa
:sectnums:

= PROG2 – Praktikum Tooling

In diesem Praktikum üben Sie mit Basis-Werkzeugen umzugehen, welche sie im
täglichen Umgang mit Ihren Projekten verwenden. Speziell, wenn sie in Gruppen
arbeiten.

Das Praktikum besteht aus 2 Teilen:

== Versionskontrolle (Git & GitHub)

In dieser Übung machen Sie Sich mit dem Git Versionskontrollsystem und den
GitHub-Kollaborationswerkzeugen vertraut, die Sie verwenden werden um den
Quellcode und Dokumentation ihrer Projekte zu verwalten.

Die Übungsanleitung finden Sie im Dokument link:git.adoc[git]. +
Die zugehörigen Dateien liegen im Handout-Verzeichnis link:../handout/git[handout/git].

== Build-Tools (Apache-Maven)

In diesem Teil üben Sie den Umgang mit dem Build-Tool Apache Maven, das sie
verwenden um die Resultate ihrer Projekte (kompilierter Code, Software-Pakete,
Dokumentation ...) zu generieren bzw. Tests auszuführen und Anwendungen zu
deployen (Repository oder Server).

Die Übungsanleitung finden Sie im Dokument link:maven.adoc[maven]. +
Die zugehörigen Dateien liegen im Handout-Verzeichnis link:../handout/maven[handout/maven].
