# Generated by Django 3.0 on 2020-02-27 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200227_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackcomment',
            old_name='what',
            new_name='thread',
        ),
        migrations.RenameField(
            model_name='versioncomment',
            old_name='what',
            new_name='thread',
        ),
        migrations.RemoveField(
            model_name='timecomment',
            name='version_ref',
        ),
        migrations.RemoveField(
            model_name='timecomment',
            name='what',
        ),
        migrations.RemoveField(
            model_name='trackcomment',
            name='track_ref',
        ),
        migrations.RemoveField(
            model_name='versioncomment',
            name='version_ref',
        ),
        migrations.AddField(
            model_name='timecomment',
            name='thread',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracker.TimeThread'),
            preserve_default=False,
        ),
    ]
