# Generated by Django 3.0 on 2020-02-27 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200227_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecomment',
            name='where',
        ),
    ]
