# Generated by Django 3.0 on 2020-04-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_timecomment_where'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='public',
        ),
    ]
