# Generated by Django 3.0 on 2020-04-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_version_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='public',
        ),
    ]
