# Generated by Django 3.0 on 2020-05-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_track_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='hash_string',
            field=models.CharField(default='impractical-freezable', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
