# Generated by Django 3.0 on 2020-05-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_session_hash_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='hash_string',
            field=models.CharField(default='grievous-badger', max_length=40, unique=True),
        ),
    ]
