# Generated by Django 3.0 on 2020-05-15 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('tracker', '0009_auto_20200512_1713'), ('tracker', '0010_auto_20200515_1545'), ('tracker', '0011_auto_20200515_1651'), ('tracker', '0012_auto_20200515_1738'), ('tracker', '0013_auto_20200515_1745'), ('tracker', '0014_auto_20200515_1912')]

    dependencies = [
        ('tracker', '0008_auto_20200506_1640'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecomment',
            name='who',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='who',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='versioncomment',
            name='who',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='timecomment',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='versioncomment',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timecomment',
            name='who',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='who',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='versioncomment',
            name='who',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='timecomment',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='versioncomment',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timecomment',
            name='who',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='who',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='versioncomment',
            name='who',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='timethread',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Version'),
        ),
        migrations.AlterUniqueTogether(
            name='timethread',
            unique_together={('version', 'relative_time')},
        ),
        migrations.AddConstraint(
            model_name='timethread',
            constraint=models.CheckConstraint(check=models.Q(relative_time__gte=0.0), name='reltime__gte_0'),
        ),
        migrations.AddConstraint(
            model_name='timethread',
            constraint=models.CheckConstraint(check=models.Q(relative_time__lte=1.0), name='reltime__lte_0'),
        ),
    ]
