# Generated by Django 3.0 on 2020-05-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_remove_session_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='parts',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
